name: kernel-test

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # as well as one pushes to PRs targeting the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  kernel-test:
    name: Testing Kernel Configuration ${{ matrix.installation }} installation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        installation:
          #- "with"
          - "without"

    steps:
    - name: Checking out xeus-cling-cmake-setup repository
      uses: actions/checkout@v2

    - name: Setting up Anaconda
      uses: s-weigand/setup-conda@v1
      channels: 'conda-forge'

    - name: Install test prerequisites
      run: |
        python -m pip install -r ./test/requirements.txt

    - name: Install xeus-cling
      run: |
        conda install xeus-cling

    - name: Building the kernels and manually installing them
      if: matrix.installation == 'without'
      run: |
        cd test
        ./install_all_kernels.sh

    - name: Building the kernels and installing them with CMake
      if: matrix.installation == 'with'
      run: |
        cd test
        ./install_all_kernels.sh install

    - name: Run Pytest to check that all Jupyter notebooks can be reproduced
      run: |
        py.test --nbval
